pipeline {
    agent any
    tools { 
        go '1.20'
    }
    options {
        skipDefaultCheckout true
    }

    stages {
        stage('Checkout') {
            steps {
                git url: "${params.GIT_REPOSITORY}", branch: "${params.GIT_BRANCH}", credentialsId: "${params.GIT_CREDENTIALS}"
            }
        }
        stage('Unit Tests') {
            steps {
                sh "go version"
            }
        }
    }
}