pipeline {
    agent any
    tools { 
        go '1.20'
    }
    environment {
        GO111MODULE = 'on'
    }
    options {
        skipDefaultCheckout true
    }

    stages {
        stage('Checkout') {
            steps {
                git url: "https://github.com/sbonaiva/${params.GIT_REPOSITORY}.git",
                    branch: "${params.GIT_BRANCH}", 
                    credentialsId: "${params.GIT_CREDENTIALS}"
            }
        }
        stage('Compile') {
            steps {
                sh 'go build ./...'
            }
        }
        stage('Test') {
            steps {
                sh 'go test ./...'
            }
        }
        stage('Coverage') {
            steps {
                echo 'skip'
            } 
        }
        stage('Containerize') {
            steps {
                dockerImage = docker.build("docker build -t sbonaiva/${params.GIT_REPOSITORY}:${BUILD_NUMBER} -f build/Dockerfile .")
            }
        }
        stage('Push') {
            steps {
                withDockerRegistry([ credentialsId: "${params.DOCKER_CREDENTIALS}", url: "" ]) {
                    dockerImage.push()
                }
            }
        }
    }
    post {
        always {
            deleteDir()
        }
    }
}